FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/TelemetryContracts/TelemetryContracts.csproj", "src/TelemetryContracts/"]
COPY ["src/TelemetryProcessor/TelemetryProcessor.csproj", "src/TelemetryProcessor/"]
RUN dotnet restore "src/TelemetryProcessor/TelemetryProcessor.csproj"
COPY src/TelemetryContracts/ src/TelemetryContracts/
COPY src/TelemetryProcessor/ src/TelemetryProcessor/
WORKDIR "/src/src/TelemetryProcessor"
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TelemetryProcessor.dll"]
